sudo: false
language: java 
dist: bionic # is ubuntu 18.04
jdk: openjdk11 
cache:
  directories:
  - "$HOME/.m2"
install: true
script:
  - mvn clean verify
  - sed -i'' -e "s/\$VERSION/${TRAVIS_TAG:=0.0.0}/" descriptor.json
  - sed -i'' -e "s/\$DATE/$(date +%Y-%m-%d)/" descriptor.json

